spring:
  datasource:
    username: root
    password: sam8659852
    url: jdbc:mysql://localhost:3306/homework?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema:
    - classpath:book.sql   
